name: Android CI App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Make gradle executable
        run: chmod +x ./gradlew

      - name: Touch local properties
        run: touch local.properties

      - name: Add Api Key
        run: echo "MY_API_KEY=\"\"" >> local.properties

      - name: Build App
        run: ./gradlew assemble

